apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "backend.name" . }}-pre-sync-check
  namespace: {{ .Values.app.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: health-check
        image: curlimages/curl:latest
        command:
          - curl
          - -sf
          - --retry
          - "20"
          - --retry-delay
          - "10"
          - --retry-connrefused
          - http://{{ include "backend.name" . }}:{{ .Values.service.targetPort }}/health/db
