apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.redis.providerClassName }}
  namespace: {{ .Values.app.namespace }}
spec:
  provider: aws
  parameters:
    region: us-west-2
    objects: |
      - objectName: "redis-creds"
        objectType: "secretsmanager"
        jmesPath:
          - path: "host"
            objectAlias: "redis_host"
          - path: "password"
            objectAlias: "redis_password"
          - path: "port"
            objectAlias: "redis_port"

  secretObjects:
    - secretName: {{ .Values.redis.k8sSecretName }}
      type: Opaque
      data:
        - objectName: redis_host
          key: REDIS_HOST
        - objectName: redis_password
          key: REDIS_PASS
        - objectName: redis_port
          key: REDIS_PORT
