apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: eks-charts-applications
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: alb-controller
            chart: aws-load-balancer-controller
            repoURL: https://aws.github.io/eks-charts
            namespace: kube-system
            targetRevision: 1.8.3
            serviceAccountName: aws-load-balancer-controller
            irsaRoleArn: "arn:aws:iam::${AWS_ACCOUNT_NUMBER}:role/eks-lb-controller-role"

  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        chart: '{{chart}}'
        targetRevision: '{{targetRevision}}'
        helm:
          values: |
            clusterName: eksdemo-cluster
            region: us-west-2
            vpcId: ${VPC_ID}
            serviceAccount:
              create: true
              name: '{{serviceAccountName}}'
              annotations:
                eks.amazonaws.com/role-arn: '{{irsaRoleArn}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
